#!/usr/bin/env bash
echo ""
echo "==========================================================================="
echo "  AVISO DE SEGURANCA / SAFETY NOTICE: SUITE EM MANUTENCAO PREVENTIVA"
echo "==========================================================================="
echo ""
echo "  [PT-BR] Os downloads e rotinas de instalacao foram temporariamente suspensos"
echo "          deste repositorio para testes internos e validacao de seguranca."
echo "          Por favor, aguarde a publicacao da versao oficial v2.0."
echo ""
echo "  [EN]    Downloads and flashing routines are temporarily paused for internal"
echo "          safety validation and regression tests. Please wait for the v2.0 release."
echo ""
echo "==========================================================================="
echo ""
exit 0
