#
# Copyright (c) 2021 Qualcomm Technologies, Inc.
#
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#
#############################
# IPQ5018 - Modem Monitor Configuration file.
#############################

# Command used to reboot the host
host_reboot_cmd = /sbin/reboot

# Command used to crash the host
host_crash_cmd = /bin/echo 'c' > /proc/sysrq-trigger

# How the modem is primarily connected to the host, "pcie" is the only supported option for 5G CPE project
modem_connection_method = pcie

# What to do when the modem crashes (after ramdump is done), "none" (exit the app),
# "crash" (call the crash command), "reboot" (call the reboot command),
# "recover" (perform hotplug to recover the modem)
modem_crash_action = recover

# What to do when the modem cannot be detected after the retries, "none" (exit the app),
# "crash" (call the crash command), "reboot" (call the reboot command)
modem_poweron_failure_action = reboot

# Detection method used for the modem, "gpio" (uses the status gpio),
# "pcie" (read the status register using lspci)
modem_detection_method = gpio

# Timeout for each power-on retry in seconds
poweron_timeout_sec = 10

# Number of times to retry the detection, performs a soft reset after each retry and hard reset on the last one
poweron_retries = 0

#############################
# PCIe hotplug
#############################

# Whether PCIe hotplug is supported or not
pcie_hotplug_support = true

# Whether the PCIe device can be removed
pcie_remove_support = true

# Command used to remove the PCIe bus for hotplug.
# Remove PCIe node for sdx
pcie_remove_cmd = /bin/echo 1 > /sys/bus/pci/slot_remove

# Command used to trigger a rescan on the PCIe bus for hotplug.
# Perform rescan for PCIe root complex for sdx
pcie_rescan_cmd = /bin/echo 1 > /sys/bus/pci/slot_rescan

#############################
# Ramdump collection
#############################

# Whether Host Ramdump collection is supported
host_ramdump_support = false

# Host Ramdump collection command
host_ramdump_cmd = ks -v -n -p /dev/ks_usb_bridge.0 -m -w /tmp/sdxdumps/

# Host Ramdump device
host_ramdump_dev = /dev/ks_usb_bridge.0

#############################
# PCIe detection method
#############################
# IPQ8074A uses MDM2AP_STATUS to determine the status of modem
# Command used to check the status of the PCIe EP
pcie_status_cmd = cat /sys/bus/pci/devices/0000\:01\:00.0/enable

# Value of the PCIe enable register when the EP is healthy
pcie_status_active_value = 1

# Value of the PCIe enable register when the EP is unhealthy
pcie_status_inactive_value = 0

#############################
# GPIO options
#############################

# MDM2AP_STATUS line
status_gpio_num = 33

# Sysfs node for gpio file access
gpio_file_path_cmd = /sys/class/gpio/gpio

# Whether the status gpio is active low (true) or not (false)
status_gpio_inverted = false

#AP2MDM_STATUS Control enabled (true) or (false)
control_ap2mdm_status_gpio = false

#AP2MDM_STATUS line
ap2mdm_status_gpio_num = 34

# Whether the status gpio is active low (true) or not (false)
ap2mdm_status_gpio_inverted = false

# power on gpio number
poweron_gpio_num = 30

# Whether the power-on gpio is active low (true) or not (false)
poweron_gpio_inverted = false

# Determine the base value of gpio
gpio_base_value_cmd = cat /sys/class/gpio/gpiochip*/base


