#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1

start_service() {
	# only cpe will run the process
	if ! cat /tmp/ipq_model | grep -qe "cpe"; then
	    exit 1
	fi
	procd_open_instance
	procd_set_param command /usr/bin/qmi_simple_ril
	procd_set_param respawn 3600 1 5
	procd_close_instance
}

