#!/bin/sh /etc/rc.common
#
#   Startup modem_datausage
#

START=99
USE_PROCD=1

PROG=/usr/bin/modem_datausage

start_service() {
	nvram set modem_datausage_flag 1
    #start-stop-daemon -S -b -x $PROG
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn
    procd_close_instance
}
